// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PlanetaryMigration.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250609032421_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlanetaryMigration.Domain.Entities.Factor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Factor");
                });

            modelBuilder.Entity("PlanetaryMigration.Domain.Entities.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });

            modelBuilder.Entity("PlanetaryMigration.Domain.Entities.PlanetFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FactorId")
                        .HasColumnType("int");

                    b.Property<int>("PlanetId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FactorId");

                    b.HasIndex("PlanetId", "FactorId")
                        .IsUnique();

                    b.ToTable("PlanetFactors");
                });

            modelBuilder.Entity("PlanetaryMigration.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedPlanetId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedPlanetId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$EphE.J6K8WIV8Q1PmVpPxegau6diBSDhai76ZJfUPWaoLkwK6Z8YC",
                            Role = 0,
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = 2,
                            AssignedPlanetId = 1,
                            PasswordHash = "$2a$11$uWYGxCp515FaX9OEDgq1HOObb4U5kfqb9reVr3Oqp/AmBXjrfhbG2",
                            Role = 1,
                            Username = "admin1"
                        });
                });

            modelBuilder.Entity("PlanetaryMigration.Domain.Entities.PlanetFactor", b =>
                {
                    b.HasOne("PlanetaryMigration.Domain.Entities.Factor", "Factor")
                        .WithMany("PlanetFactors")
                        .HasForeignKey("FactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanetaryMigration.Domain.Entities.Planet", "Planet")
                        .WithMany("PlanetFactors")
                        .HasForeignKey("PlanetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factor");

                    b.Navigation("Planet");
                });

            modelBuilder.Entity("PlanetaryMigration.Domain.Entities.User", b =>
                {
                    b.HasOne("PlanetaryMigration.Domain.Entities.Planet", "AssignedPlanet")
                        .WithMany()
                        .HasForeignKey("AssignedPlanetId");

                    b.Navigation("AssignedPlanet");
                });

            modelBuilder.Entity("PlanetaryMigration.Domain.Entities.Factor", b =>
                {
                    b.Navigation("PlanetFactors");
                });

            modelBuilder.Entity("PlanetaryMigration.Domain.Entities.Planet", b =>
                {
                    b.Navigation("PlanetFactors");
                });
#pragma warning restore 612, 618
        }
    }
}
